### ISSUE TITLE
攻击问题

### ISSUE THREAD

**Issue by hfw99** [BruceQiu1996/ArpSpoofing#1]
点击工具咋把攻击机给搞断网了

**Comment by BruceQiu1996** [comment]
好像是有这个问题，目前属于两败俱伤了，我会找时间处理该问题

**Comment by BruceQiu1996** [comment]
@hfw99 原理是因为你把自己的mac地址和网关做了绑定发送给了目标机器，导致你自己的ip和mac绑定也出错了，所以暂时只能攻击对方的时候自己也会没办法收到数据包
